# This is a basic workflow to help you get started with Actions

name: GaoT

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # - name: Remote Script Executor
      # - uses: Binozo/GitHubActionRemoteScriptExecutor@v1.4
      #   with:
      #     server-address: 192.200.150.63
      #     script-name: myscript.sh
      #     password: ${{ secrets.server_password }}
